name: compile-pdf
on: push
jobs:
  compile-pdf:
    name: Compile PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bylaws.tex
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: bylaws.pdf
